### PR TITLE
added back oboe, reduced lag for huge files

### PR DESCRIPTION
**Pull request by abhisuri97**
(also fixed indentation in index.js)
Stats (running with 16 GB RAM and ~ 2.4 gb js heap space)
```
40 MB: 7.52 sec (18 trials) Memory usage: ~28 MB
90 MB: 15.22 sec (9 trials) Memory usage: ~49 MB
180 MB: 33.29 sec (8 trials) Memory usage: ~ 100 MB
270 MB: 48.20 sec (9 trials) Memory usage: ~ 145 MB
512 MB (self constructed file): 91.30 sec (2 trials)
2.1 GB file (self constructed file): 368.1 sec (2 trials)
2.2 GB file (self constructed): Fail to load all points. Reached chrome memory limit 
```

### CODE REVIEW

**Comment by abhisuri97** [comment]
#15 #16

**Comment by theopolisme** [comment]
Can you please remove the indentation changes from this PR? I'm not averse to modifying it (via a second pull request), but it makes it impossible to review the specific code changes you made (since *everything* is highlighted as changed).

Thanks, excited to get this merged in ASAP!

**Comment by abhisuri97** [comment]
Fixed to adapt to your style

**Comment by abhisuri97** [comment]
bump @theopolisme

**Comment by abhisuri97** [comment]
bump again

**Comment by justanotheramateur** [comment]
Sounds wonderful. Thanks for working on this!

**Comment by theopolisme** [comment]
Thanks and sorry for the huge delay on this! Completely forgot about it. You rock, @abhisuri97.

**Pull request merged**
